class AuthException(Exception): ...
class InvalidCredentialsException(AuthException): ...
class UserAlreadyExistsException(AuthException): ...
class TokenExpiredException(AuthException): ...
class UnauthorizedException(AuthException): ...
