"""Initial Async Migration

Revision ID: 33bf4a364fa2
Revises: 
Create Date: 2026-08-04 00:25:03.210075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33bf4a364fa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mastery_profiles')
    op.drop_table('exam_blueprints')
    op.drop_table('user_progress')
    op.add_column('certifications', sa.Column('level', sa.String(), nullable=False))
    op.add_column('certifications', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('certifications', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('certifications', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('certifications', 'exam_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('certifications', 'version')
    op.drop_column('certifications', 'created_at')
    op.alter_column('question_comments', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('question_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('questions', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('questions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('questions', 'explanation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('questions', 'objective_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('questions', 'misconception_tag',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('questions_objective_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'study_objectives', ['objective_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'created_at')
    op.alter_column('sessions', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'score',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('sessions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('sessions_blueprint_id_fkey', 'sessions', type_='foreignkey')
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'blueprint_id')
    op.drop_column('sessions', 'mode')
    op.add_column('study_objectives', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.alter_column('study_objectives', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('study_objectives', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('study_objectives', 'weight',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=True)
    op.create_foreign_key(None, 'study_objectives', 'study_objectives', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('study_objectives', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_objectives', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'study_objectives', type_='foreignkey')
    op.alter_column('study_objectives', 'weight',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=False)
    op.alter_column('study_objectives', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('study_objectives', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('study_objectives', 'parent_id')
    op.add_column('sessions', sa.Column('mode', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('blueprint_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key('sessions_blueprint_id_fkey', 'sessions', 'exam_blueprints', ['blueprint_id'], ['id'])
    op.alter_column('sessions', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sessions', 'score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('questions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_objective_id_fkey', 'questions', 'study_objectives', ['objective_id'], ['id'])
    op.alter_column('questions', 'misconception_tag',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('questions', 'objective_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('questions', 'explanation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('questions', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('questions', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('question_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('question_comments', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('certifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('certifications', sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('certifications', 'exam_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('certifications', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('certifications', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('certifications', 'description')
    op.drop_column('certifications', 'level')
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('certification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sessions_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('average_score', sa.NUMERIC(), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], name='user_progress_certification_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='user_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_progress_pkey'),
    sa.UniqueConstraint('user_id', 'certification_id', name='user_progress_user_id_certification_id_key')
    )
    op.create_table('exam_blueprints',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('certification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passing_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distribution', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], name='exam_blueprints_certification_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='exam_blueprints_pkey')
    )
    op.create_table('mastery_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('certification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('objective_mastery', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('overall_mastery', sa.NUMERIC(), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('readiness_score', sa.NUMERIC(), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], name='mastery_profiles_certification_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='mastery_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mastery_profiles_pkey'),
    sa.UniqueConstraint('user_id', 'certification_id', name='mastery_profiles_user_id_certification_id_key')
    )
    # ### end Alembic commands ###
